
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ExchangeRate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ExchangeRate
 * 
 */
export type ExchangeRateModel = runtime.Types.Result.DefaultSelection<Prisma.$ExchangeRatePayload>

export type AggregateExchangeRate = {
  _count: ExchangeRateCountAggregateOutputType | null
  _avg: ExchangeRateAvgAggregateOutputType | null
  _sum: ExchangeRateSumAggregateOutputType | null
  _min: ExchangeRateMinAggregateOutputType | null
  _max: ExchangeRateMaxAggregateOutputType | null
}

export type ExchangeRateAvgAggregateOutputType = {
  id: number | null
  price: runtime.Decimal | null
  sourceId: number | null
  variantion: number | null
}

export type ExchangeRateSumAggregateOutputType = {
  id: number | null
  price: runtime.Decimal | null
  sourceId: number | null
  variantion: number | null
}

export type ExchangeRateMinAggregateOutputType = {
  id: number | null
  price: runtime.Decimal | null
  sourceId: number | null
  trend: $Enums.Trend | null
  variantion: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ExchangeRateMaxAggregateOutputType = {
  id: number | null
  price: runtime.Decimal | null
  sourceId: number | null
  trend: $Enums.Trend | null
  variantion: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ExchangeRateCountAggregateOutputType = {
  id: number
  price: number
  sourceId: number
  trend: number
  variantion: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ExchangeRateAvgAggregateInputType = {
  id?: true
  price?: true
  sourceId?: true
  variantion?: true
}

export type ExchangeRateSumAggregateInputType = {
  id?: true
  price?: true
  sourceId?: true
  variantion?: true
}

export type ExchangeRateMinAggregateInputType = {
  id?: true
  price?: true
  sourceId?: true
  trend?: true
  variantion?: true
  createdAt?: true
  updatedAt?: true
}

export type ExchangeRateMaxAggregateInputType = {
  id?: true
  price?: true
  sourceId?: true
  trend?: true
  variantion?: true
  createdAt?: true
  updatedAt?: true
}

export type ExchangeRateCountAggregateInputType = {
  id?: true
  price?: true
  sourceId?: true
  trend?: true
  variantion?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ExchangeRateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExchangeRate to aggregate.
   */
  where?: Prisma.ExchangeRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExchangeRates to fetch.
   */
  orderBy?: Prisma.ExchangeRateOrderByWithRelationInput | Prisma.ExchangeRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExchangeRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExchangeRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExchangeRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ExchangeRates
  **/
  _count?: true | ExchangeRateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExchangeRateAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExchangeRateSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExchangeRateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExchangeRateMaxAggregateInputType
}

export type GetExchangeRateAggregateType<T extends ExchangeRateAggregateArgs> = {
      [P in keyof T & keyof AggregateExchangeRate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExchangeRate[P]>
    : Prisma.GetScalarType<T[P], AggregateExchangeRate[P]>
}




export type ExchangeRateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExchangeRateWhereInput
  orderBy?: Prisma.ExchangeRateOrderByWithAggregationInput | Prisma.ExchangeRateOrderByWithAggregationInput[]
  by: Prisma.ExchangeRateScalarFieldEnum[] | Prisma.ExchangeRateScalarFieldEnum
  having?: Prisma.ExchangeRateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExchangeRateCountAggregateInputType | true
  _avg?: ExchangeRateAvgAggregateInputType
  _sum?: ExchangeRateSumAggregateInputType
  _min?: ExchangeRateMinAggregateInputType
  _max?: ExchangeRateMaxAggregateInputType
}

export type ExchangeRateGroupByOutputType = {
  id: number
  price: runtime.Decimal
  sourceId: number
  trend: $Enums.Trend
  variantion: number
  createdAt: Date
  updatedAt: Date
  _count: ExchangeRateCountAggregateOutputType | null
  _avg: ExchangeRateAvgAggregateOutputType | null
  _sum: ExchangeRateSumAggregateOutputType | null
  _min: ExchangeRateMinAggregateOutputType | null
  _max: ExchangeRateMaxAggregateOutputType | null
}

export type GetExchangeRateGroupByPayload<T extends ExchangeRateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExchangeRateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExchangeRateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExchangeRateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExchangeRateGroupByOutputType[P]>
      }
    >
  >



export type ExchangeRateWhereInput = {
  AND?: Prisma.ExchangeRateWhereInput | Prisma.ExchangeRateWhereInput[]
  OR?: Prisma.ExchangeRateWhereInput[]
  NOT?: Prisma.ExchangeRateWhereInput | Prisma.ExchangeRateWhereInput[]
  id?: Prisma.IntFilter<"ExchangeRate"> | number
  price?: Prisma.DecimalFilter<"ExchangeRate"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId?: Prisma.IntFilter<"ExchangeRate"> | number
  trend?: Prisma.EnumTrendFilter<"ExchangeRate"> | $Enums.Trend
  variantion?: Prisma.FloatFilter<"ExchangeRate"> | number
  createdAt?: Prisma.DateTimeFilter<"ExchangeRate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ExchangeRate"> | Date | string
  source?: Prisma.XOR<Prisma.SourcesScalarRelationFilter, Prisma.SourcesWhereInput>
}

export type ExchangeRateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  trend?: Prisma.SortOrder
  variantion?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  source?: Prisma.SourcesOrderByWithRelationInput
}

export type ExchangeRateWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ExchangeRateWhereInput | Prisma.ExchangeRateWhereInput[]
  OR?: Prisma.ExchangeRateWhereInput[]
  NOT?: Prisma.ExchangeRateWhereInput | Prisma.ExchangeRateWhereInput[]
  price?: Prisma.DecimalFilter<"ExchangeRate"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId?: Prisma.IntFilter<"ExchangeRate"> | number
  trend?: Prisma.EnumTrendFilter<"ExchangeRate"> | $Enums.Trend
  variantion?: Prisma.FloatFilter<"ExchangeRate"> | number
  createdAt?: Prisma.DateTimeFilter<"ExchangeRate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ExchangeRate"> | Date | string
  source?: Prisma.XOR<Prisma.SourcesScalarRelationFilter, Prisma.SourcesWhereInput>
}, "id">

export type ExchangeRateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  trend?: Prisma.SortOrder
  variantion?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ExchangeRateCountOrderByAggregateInput
  _avg?: Prisma.ExchangeRateAvgOrderByAggregateInput
  _max?: Prisma.ExchangeRateMaxOrderByAggregateInput
  _min?: Prisma.ExchangeRateMinOrderByAggregateInput
  _sum?: Prisma.ExchangeRateSumOrderByAggregateInput
}

export type ExchangeRateScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExchangeRateScalarWhereWithAggregatesInput | Prisma.ExchangeRateScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExchangeRateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExchangeRateScalarWhereWithAggregatesInput | Prisma.ExchangeRateScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ExchangeRate"> | number
  price?: Prisma.DecimalWithAggregatesFilter<"ExchangeRate"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId?: Prisma.IntWithAggregatesFilter<"ExchangeRate"> | number
  trend?: Prisma.EnumTrendWithAggregatesFilter<"ExchangeRate"> | $Enums.Trend
  variantion?: Prisma.FloatWithAggregatesFilter<"ExchangeRate"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ExchangeRate"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ExchangeRate"> | Date | string
}

export type ExchangeRateCreateInput = {
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  trend: $Enums.Trend
  variantion: number
  createdAt?: Date | string
  updatedAt?: Date | string
  source: Prisma.SourcesCreateNestedOneWithoutExchangeRatesInput
}

export type ExchangeRateUncheckedCreateInput = {
  id?: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId: number
  trend: $Enums.Trend
  variantion: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExchangeRateUpdateInput = {
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  trend?: Prisma.EnumTrendFieldUpdateOperationsInput | $Enums.Trend
  variantion?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.SourcesUpdateOneRequiredWithoutExchangeRatesNestedInput
}

export type ExchangeRateUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId?: Prisma.IntFieldUpdateOperationsInput | number
  trend?: Prisma.EnumTrendFieldUpdateOperationsInput | $Enums.Trend
  variantion?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExchangeRateCreateManyInput = {
  id?: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId: number
  trend: $Enums.Trend
  variantion: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExchangeRateUpdateManyMutationInput = {
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  trend?: Prisma.EnumTrendFieldUpdateOperationsInput | $Enums.Trend
  variantion?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExchangeRateUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId?: Prisma.IntFieldUpdateOperationsInput | number
  trend?: Prisma.EnumTrendFieldUpdateOperationsInput | $Enums.Trend
  variantion?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExchangeRateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  trend?: Prisma.SortOrder
  variantion?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ExchangeRateAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  variantion?: Prisma.SortOrder
}

export type ExchangeRateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  trend?: Prisma.SortOrder
  variantion?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ExchangeRateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  trend?: Prisma.SortOrder
  variantion?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ExchangeRateSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  variantion?: Prisma.SortOrder
}

export type ExchangeRateListRelationFilter = {
  every?: Prisma.ExchangeRateWhereInput
  some?: Prisma.ExchangeRateWhereInput
  none?: Prisma.ExchangeRateWhereInput
}

export type ExchangeRateOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type EnumTrendFieldUpdateOperationsInput = {
  set?: $Enums.Trend
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ExchangeRateCreateNestedManyWithoutSourceInput = {
  create?: Prisma.XOR<Prisma.ExchangeRateCreateWithoutSourceInput, Prisma.ExchangeRateUncheckedCreateWithoutSourceInput> | Prisma.ExchangeRateCreateWithoutSourceInput[] | Prisma.ExchangeRateUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.ExchangeRateCreateOrConnectWithoutSourceInput | Prisma.ExchangeRateCreateOrConnectWithoutSourceInput[]
  createMany?: Prisma.ExchangeRateCreateManySourceInputEnvelope
  connect?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
}

export type ExchangeRateUncheckedCreateNestedManyWithoutSourceInput = {
  create?: Prisma.XOR<Prisma.ExchangeRateCreateWithoutSourceInput, Prisma.ExchangeRateUncheckedCreateWithoutSourceInput> | Prisma.ExchangeRateCreateWithoutSourceInput[] | Prisma.ExchangeRateUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.ExchangeRateCreateOrConnectWithoutSourceInput | Prisma.ExchangeRateCreateOrConnectWithoutSourceInput[]
  createMany?: Prisma.ExchangeRateCreateManySourceInputEnvelope
  connect?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
}

export type ExchangeRateUpdateManyWithoutSourceNestedInput = {
  create?: Prisma.XOR<Prisma.ExchangeRateCreateWithoutSourceInput, Prisma.ExchangeRateUncheckedCreateWithoutSourceInput> | Prisma.ExchangeRateCreateWithoutSourceInput[] | Prisma.ExchangeRateUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.ExchangeRateCreateOrConnectWithoutSourceInput | Prisma.ExchangeRateCreateOrConnectWithoutSourceInput[]
  upsert?: Prisma.ExchangeRateUpsertWithWhereUniqueWithoutSourceInput | Prisma.ExchangeRateUpsertWithWhereUniqueWithoutSourceInput[]
  createMany?: Prisma.ExchangeRateCreateManySourceInputEnvelope
  set?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  disconnect?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  delete?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  connect?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  update?: Prisma.ExchangeRateUpdateWithWhereUniqueWithoutSourceInput | Prisma.ExchangeRateUpdateWithWhereUniqueWithoutSourceInput[]
  updateMany?: Prisma.ExchangeRateUpdateManyWithWhereWithoutSourceInput | Prisma.ExchangeRateUpdateManyWithWhereWithoutSourceInput[]
  deleteMany?: Prisma.ExchangeRateScalarWhereInput | Prisma.ExchangeRateScalarWhereInput[]
}

export type ExchangeRateUncheckedUpdateManyWithoutSourceNestedInput = {
  create?: Prisma.XOR<Prisma.ExchangeRateCreateWithoutSourceInput, Prisma.ExchangeRateUncheckedCreateWithoutSourceInput> | Prisma.ExchangeRateCreateWithoutSourceInput[] | Prisma.ExchangeRateUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.ExchangeRateCreateOrConnectWithoutSourceInput | Prisma.ExchangeRateCreateOrConnectWithoutSourceInput[]
  upsert?: Prisma.ExchangeRateUpsertWithWhereUniqueWithoutSourceInput | Prisma.ExchangeRateUpsertWithWhereUniqueWithoutSourceInput[]
  createMany?: Prisma.ExchangeRateCreateManySourceInputEnvelope
  set?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  disconnect?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  delete?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  connect?: Prisma.ExchangeRateWhereUniqueInput | Prisma.ExchangeRateWhereUniqueInput[]
  update?: Prisma.ExchangeRateUpdateWithWhereUniqueWithoutSourceInput | Prisma.ExchangeRateUpdateWithWhereUniqueWithoutSourceInput[]
  updateMany?: Prisma.ExchangeRateUpdateManyWithWhereWithoutSourceInput | Prisma.ExchangeRateUpdateManyWithWhereWithoutSourceInput[]
  deleteMany?: Prisma.ExchangeRateScalarWhereInput | Prisma.ExchangeRateScalarWhereInput[]
}

export type ExchangeRateCreateWithoutSourceInput = {
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  trend: $Enums.Trend
  variantion: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExchangeRateUncheckedCreateWithoutSourceInput = {
  id?: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  trend: $Enums.Trend
  variantion: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExchangeRateCreateOrConnectWithoutSourceInput = {
  where: Prisma.ExchangeRateWhereUniqueInput
  create: Prisma.XOR<Prisma.ExchangeRateCreateWithoutSourceInput, Prisma.ExchangeRateUncheckedCreateWithoutSourceInput>
}

export type ExchangeRateCreateManySourceInputEnvelope = {
  data: Prisma.ExchangeRateCreateManySourceInput | Prisma.ExchangeRateCreateManySourceInput[]
  skipDuplicates?: boolean
}

export type ExchangeRateUpsertWithWhereUniqueWithoutSourceInput = {
  where: Prisma.ExchangeRateWhereUniqueInput
  update: Prisma.XOR<Prisma.ExchangeRateUpdateWithoutSourceInput, Prisma.ExchangeRateUncheckedUpdateWithoutSourceInput>
  create: Prisma.XOR<Prisma.ExchangeRateCreateWithoutSourceInput, Prisma.ExchangeRateUncheckedCreateWithoutSourceInput>
}

export type ExchangeRateUpdateWithWhereUniqueWithoutSourceInput = {
  where: Prisma.ExchangeRateWhereUniqueInput
  data: Prisma.XOR<Prisma.ExchangeRateUpdateWithoutSourceInput, Prisma.ExchangeRateUncheckedUpdateWithoutSourceInput>
}

export type ExchangeRateUpdateManyWithWhereWithoutSourceInput = {
  where: Prisma.ExchangeRateScalarWhereInput
  data: Prisma.XOR<Prisma.ExchangeRateUpdateManyMutationInput, Prisma.ExchangeRateUncheckedUpdateManyWithoutSourceInput>
}

export type ExchangeRateScalarWhereInput = {
  AND?: Prisma.ExchangeRateScalarWhereInput | Prisma.ExchangeRateScalarWhereInput[]
  OR?: Prisma.ExchangeRateScalarWhereInput[]
  NOT?: Prisma.ExchangeRateScalarWhereInput | Prisma.ExchangeRateScalarWhereInput[]
  id?: Prisma.IntFilter<"ExchangeRate"> | number
  price?: Prisma.DecimalFilter<"ExchangeRate"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sourceId?: Prisma.IntFilter<"ExchangeRate"> | number
  trend?: Prisma.EnumTrendFilter<"ExchangeRate"> | $Enums.Trend
  variantion?: Prisma.FloatFilter<"ExchangeRate"> | number
  createdAt?: Prisma.DateTimeFilter<"ExchangeRate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ExchangeRate"> | Date | string
}

export type ExchangeRateCreateManySourceInput = {
  id?: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  trend: $Enums.Trend
  variantion: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExchangeRateUpdateWithoutSourceInput = {
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  trend?: Prisma.EnumTrendFieldUpdateOperationsInput | $Enums.Trend
  variantion?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExchangeRateUncheckedUpdateWithoutSourceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  trend?: Prisma.EnumTrendFieldUpdateOperationsInput | $Enums.Trend
  variantion?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExchangeRateUncheckedUpdateManyWithoutSourceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  trend?: Prisma.EnumTrendFieldUpdateOperationsInput | $Enums.Trend
  variantion?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ExchangeRateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  price?: boolean
  sourceId?: boolean
  trend?: boolean
  variantion?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  source?: boolean | Prisma.SourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exchangeRate"]>

export type ExchangeRateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  price?: boolean
  sourceId?: boolean
  trend?: boolean
  variantion?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  source?: boolean | Prisma.SourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exchangeRate"]>

export type ExchangeRateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  price?: boolean
  sourceId?: boolean
  trend?: boolean
  variantion?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  source?: boolean | Prisma.SourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exchangeRate"]>

export type ExchangeRateSelectScalar = {
  id?: boolean
  price?: boolean
  sourceId?: boolean
  trend?: boolean
  variantion?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ExchangeRateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "price" | "sourceId" | "trend" | "variantion" | "createdAt" | "updatedAt", ExtArgs["result"]["exchangeRate"]>
export type ExchangeRateInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.SourcesDefaultArgs<ExtArgs>
}
export type ExchangeRateIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.SourcesDefaultArgs<ExtArgs>
}
export type ExchangeRateIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.SourcesDefaultArgs<ExtArgs>
}

export type $ExchangeRatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ExchangeRate"
  objects: {
    source: Prisma.$SourcesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    price: runtime.Decimal
    sourceId: number
    trend: $Enums.Trend
    variantion: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["exchangeRate"]>
  composites: {}
}

export type ExchangeRateGetPayload<S extends boolean | null | undefined | ExchangeRateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload, S>

export type ExchangeRateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExchangeRateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExchangeRateCountAggregateInputType | true
  }

export interface ExchangeRateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ExchangeRate'], meta: { name: 'ExchangeRate' } }
  /**
   * Find zero or one ExchangeRate that matches the filter.
   * @param {ExchangeRateFindUniqueArgs} args - Arguments to find a ExchangeRate
   * @example
   * // Get one ExchangeRate
   * const exchangeRate = await prisma.exchangeRate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExchangeRateFindUniqueArgs>(args: Prisma.SelectSubset<T, ExchangeRateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ExchangeRate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExchangeRateFindUniqueOrThrowArgs} args - Arguments to find a ExchangeRate
   * @example
   * // Get one ExchangeRate
   * const exchangeRate = await prisma.exchangeRate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExchangeRateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExchangeRateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExchangeRate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExchangeRateFindFirstArgs} args - Arguments to find a ExchangeRate
   * @example
   * // Get one ExchangeRate
   * const exchangeRate = await prisma.exchangeRate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExchangeRateFindFirstArgs>(args?: Prisma.SelectSubset<T, ExchangeRateFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExchangeRate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExchangeRateFindFirstOrThrowArgs} args - Arguments to find a ExchangeRate
   * @example
   * // Get one ExchangeRate
   * const exchangeRate = await prisma.exchangeRate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExchangeRateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExchangeRateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ExchangeRates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExchangeRateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExchangeRates
   * const exchangeRates = await prisma.exchangeRate.findMany()
   * 
   * // Get first 10 ExchangeRates
   * const exchangeRates = await prisma.exchangeRate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const exchangeRateWithIdOnly = await prisma.exchangeRate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExchangeRateFindManyArgs>(args?: Prisma.SelectSubset<T, ExchangeRateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ExchangeRate.
   * @param {ExchangeRateCreateArgs} args - Arguments to create a ExchangeRate.
   * @example
   * // Create one ExchangeRate
   * const ExchangeRate = await prisma.exchangeRate.create({
   *   data: {
   *     // ... data to create a ExchangeRate
   *   }
   * })
   * 
   */
  create<T extends ExchangeRateCreateArgs>(args: Prisma.SelectSubset<T, ExchangeRateCreateArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ExchangeRates.
   * @param {ExchangeRateCreateManyArgs} args - Arguments to create many ExchangeRates.
   * @example
   * // Create many ExchangeRates
   * const exchangeRate = await prisma.exchangeRate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExchangeRateCreateManyArgs>(args?: Prisma.SelectSubset<T, ExchangeRateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ExchangeRates and returns the data saved in the database.
   * @param {ExchangeRateCreateManyAndReturnArgs} args - Arguments to create many ExchangeRates.
   * @example
   * // Create many ExchangeRates
   * const exchangeRate = await prisma.exchangeRate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ExchangeRates and only return the `id`
   * const exchangeRateWithIdOnly = await prisma.exchangeRate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExchangeRateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExchangeRateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ExchangeRate.
   * @param {ExchangeRateDeleteArgs} args - Arguments to delete one ExchangeRate.
   * @example
   * // Delete one ExchangeRate
   * const ExchangeRate = await prisma.exchangeRate.delete({
   *   where: {
   *     // ... filter to delete one ExchangeRate
   *   }
   * })
   * 
   */
  delete<T extends ExchangeRateDeleteArgs>(args: Prisma.SelectSubset<T, ExchangeRateDeleteArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ExchangeRate.
   * @param {ExchangeRateUpdateArgs} args - Arguments to update one ExchangeRate.
   * @example
   * // Update one ExchangeRate
   * const exchangeRate = await prisma.exchangeRate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExchangeRateUpdateArgs>(args: Prisma.SelectSubset<T, ExchangeRateUpdateArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ExchangeRates.
   * @param {ExchangeRateDeleteManyArgs} args - Arguments to filter ExchangeRates to delete.
   * @example
   * // Delete a few ExchangeRates
   * const { count } = await prisma.exchangeRate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExchangeRateDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExchangeRateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExchangeRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExchangeRateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExchangeRates
   * const exchangeRate = await prisma.exchangeRate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExchangeRateUpdateManyArgs>(args: Prisma.SelectSubset<T, ExchangeRateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExchangeRates and returns the data updated in the database.
   * @param {ExchangeRateUpdateManyAndReturnArgs} args - Arguments to update many ExchangeRates.
   * @example
   * // Update many ExchangeRates
   * const exchangeRate = await prisma.exchangeRate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ExchangeRates and only return the `id`
   * const exchangeRateWithIdOnly = await prisma.exchangeRate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExchangeRateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExchangeRateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ExchangeRate.
   * @param {ExchangeRateUpsertArgs} args - Arguments to update or create a ExchangeRate.
   * @example
   * // Update or create a ExchangeRate
   * const exchangeRate = await prisma.exchangeRate.upsert({
   *   create: {
   *     // ... data to create a ExchangeRate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExchangeRate we want to update
   *   }
   * })
   */
  upsert<T extends ExchangeRateUpsertArgs>(args: Prisma.SelectSubset<T, ExchangeRateUpsertArgs<ExtArgs>>): Prisma.Prisma__ExchangeRateClient<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ExchangeRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExchangeRateCountArgs} args - Arguments to filter ExchangeRates to count.
   * @example
   * // Count the number of ExchangeRates
   * const count = await prisma.exchangeRate.count({
   *   where: {
   *     // ... the filter for the ExchangeRates we want to count
   *   }
   * })
  **/
  count<T extends ExchangeRateCountArgs>(
    args?: Prisma.Subset<T, ExchangeRateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExchangeRateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ExchangeRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExchangeRateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExchangeRateAggregateArgs>(args: Prisma.Subset<T, ExchangeRateAggregateArgs>): Prisma.PrismaPromise<GetExchangeRateAggregateType<T>>

  /**
   * Group by ExchangeRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExchangeRateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExchangeRateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExchangeRateGroupByArgs['orderBy'] }
      : { orderBy?: ExchangeRateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExchangeRateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExchangeRateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ExchangeRate model
 */
readonly fields: ExchangeRateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ExchangeRate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExchangeRateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  source<T extends Prisma.SourcesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SourcesDefaultArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ExchangeRate model
 */
export interface ExchangeRateFieldRefs {
  readonly id: Prisma.FieldRef<"ExchangeRate", 'Int'>
  readonly price: Prisma.FieldRef<"ExchangeRate", 'Decimal'>
  readonly sourceId: Prisma.FieldRef<"ExchangeRate", 'Int'>
  readonly trend: Prisma.FieldRef<"ExchangeRate", 'Trend'>
  readonly variantion: Prisma.FieldRef<"ExchangeRate", 'Float'>
  readonly createdAt: Prisma.FieldRef<"ExchangeRate", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ExchangeRate", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ExchangeRate findUnique
 */
export type ExchangeRateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * Filter, which ExchangeRate to fetch.
   */
  where: Prisma.ExchangeRateWhereUniqueInput
}

/**
 * ExchangeRate findUniqueOrThrow
 */
export type ExchangeRateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * Filter, which ExchangeRate to fetch.
   */
  where: Prisma.ExchangeRateWhereUniqueInput
}

/**
 * ExchangeRate findFirst
 */
export type ExchangeRateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * Filter, which ExchangeRate to fetch.
   */
  where?: Prisma.ExchangeRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExchangeRates to fetch.
   */
  orderBy?: Prisma.ExchangeRateOrderByWithRelationInput | Prisma.ExchangeRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExchangeRates.
   */
  cursor?: Prisma.ExchangeRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExchangeRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExchangeRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExchangeRates.
   */
  distinct?: Prisma.ExchangeRateScalarFieldEnum | Prisma.ExchangeRateScalarFieldEnum[]
}

/**
 * ExchangeRate findFirstOrThrow
 */
export type ExchangeRateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * Filter, which ExchangeRate to fetch.
   */
  where?: Prisma.ExchangeRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExchangeRates to fetch.
   */
  orderBy?: Prisma.ExchangeRateOrderByWithRelationInput | Prisma.ExchangeRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExchangeRates.
   */
  cursor?: Prisma.ExchangeRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExchangeRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExchangeRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExchangeRates.
   */
  distinct?: Prisma.ExchangeRateScalarFieldEnum | Prisma.ExchangeRateScalarFieldEnum[]
}

/**
 * ExchangeRate findMany
 */
export type ExchangeRateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * Filter, which ExchangeRates to fetch.
   */
  where?: Prisma.ExchangeRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExchangeRates to fetch.
   */
  orderBy?: Prisma.ExchangeRateOrderByWithRelationInput | Prisma.ExchangeRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ExchangeRates.
   */
  cursor?: Prisma.ExchangeRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExchangeRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExchangeRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExchangeRates.
   */
  distinct?: Prisma.ExchangeRateScalarFieldEnum | Prisma.ExchangeRateScalarFieldEnum[]
}

/**
 * ExchangeRate create
 */
export type ExchangeRateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * The data needed to create a ExchangeRate.
   */
  data: Prisma.XOR<Prisma.ExchangeRateCreateInput, Prisma.ExchangeRateUncheckedCreateInput>
}

/**
 * ExchangeRate createMany
 */
export type ExchangeRateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ExchangeRates.
   */
  data: Prisma.ExchangeRateCreateManyInput | Prisma.ExchangeRateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ExchangeRate createManyAndReturn
 */
export type ExchangeRateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * The data used to create many ExchangeRates.
   */
  data: Prisma.ExchangeRateCreateManyInput | Prisma.ExchangeRateCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ExchangeRate update
 */
export type ExchangeRateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * The data needed to update a ExchangeRate.
   */
  data: Prisma.XOR<Prisma.ExchangeRateUpdateInput, Prisma.ExchangeRateUncheckedUpdateInput>
  /**
   * Choose, which ExchangeRate to update.
   */
  where: Prisma.ExchangeRateWhereUniqueInput
}

/**
 * ExchangeRate updateMany
 */
export type ExchangeRateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ExchangeRates.
   */
  data: Prisma.XOR<Prisma.ExchangeRateUpdateManyMutationInput, Prisma.ExchangeRateUncheckedUpdateManyInput>
  /**
   * Filter which ExchangeRates to update
   */
  where?: Prisma.ExchangeRateWhereInput
  /**
   * Limit how many ExchangeRates to update.
   */
  limit?: number
}

/**
 * ExchangeRate updateManyAndReturn
 */
export type ExchangeRateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * The data used to update ExchangeRates.
   */
  data: Prisma.XOR<Prisma.ExchangeRateUpdateManyMutationInput, Prisma.ExchangeRateUncheckedUpdateManyInput>
  /**
   * Filter which ExchangeRates to update
   */
  where?: Prisma.ExchangeRateWhereInput
  /**
   * Limit how many ExchangeRates to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ExchangeRate upsert
 */
export type ExchangeRateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * The filter to search for the ExchangeRate to update in case it exists.
   */
  where: Prisma.ExchangeRateWhereUniqueInput
  /**
   * In case the ExchangeRate found by the `where` argument doesn't exist, create a new ExchangeRate with this data.
   */
  create: Prisma.XOR<Prisma.ExchangeRateCreateInput, Prisma.ExchangeRateUncheckedCreateInput>
  /**
   * In case the ExchangeRate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExchangeRateUpdateInput, Prisma.ExchangeRateUncheckedUpdateInput>
}

/**
 * ExchangeRate delete
 */
export type ExchangeRateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  /**
   * Filter which ExchangeRate to delete.
   */
  where: Prisma.ExchangeRateWhereUniqueInput
}

/**
 * ExchangeRate deleteMany
 */
export type ExchangeRateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExchangeRates to delete
   */
  where?: Prisma.ExchangeRateWhereInput
  /**
   * Limit how many ExchangeRates to delete.
   */
  limit?: number
}

/**
 * ExchangeRate without action
 */
export type ExchangeRateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
}
