
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Sources` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Sources
 * 
 */
export type SourcesModel = runtime.Types.Result.DefaultSelection<Prisma.$SourcesPayload>

export type AggregateSources = {
  _count: SourcesCountAggregateOutputType | null
  _avg: SourcesAvgAggregateOutputType | null
  _sum: SourcesSumAggregateOutputType | null
  _min: SourcesMinAggregateOutputType | null
  _max: SourcesMaxAggregateOutputType | null
}

export type SourcesAvgAggregateOutputType = {
  id: number | null
  lastPrice: runtime.Decimal | null
  weight: number | null
}

export type SourcesSumAggregateOutputType = {
  id: number | null
  lastPrice: runtime.Decimal | null
  weight: number | null
}

export type SourcesMinAggregateOutputType = {
  id: number | null
  name: string | null
  isActive: boolean | null
  lastPrice: runtime.Decimal | null
  weight: number | null
}

export type SourcesMaxAggregateOutputType = {
  id: number | null
  name: string | null
  isActive: boolean | null
  lastPrice: runtime.Decimal | null
  weight: number | null
}

export type SourcesCountAggregateOutputType = {
  id: number
  name: number
  isActive: number
  lastPrice: number
  weight: number
  _all: number
}


export type SourcesAvgAggregateInputType = {
  id?: true
  lastPrice?: true
  weight?: true
}

export type SourcesSumAggregateInputType = {
  id?: true
  lastPrice?: true
  weight?: true
}

export type SourcesMinAggregateInputType = {
  id?: true
  name?: true
  isActive?: true
  lastPrice?: true
  weight?: true
}

export type SourcesMaxAggregateInputType = {
  id?: true
  name?: true
  isActive?: true
  lastPrice?: true
  weight?: true
}

export type SourcesCountAggregateInputType = {
  id?: true
  name?: true
  isActive?: true
  lastPrice?: true
  weight?: true
  _all?: true
}

export type SourcesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sources to aggregate.
   */
  where?: Prisma.SourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sources to fetch.
   */
  orderBy?: Prisma.SourcesOrderByWithRelationInput | Prisma.SourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Sources
  **/
  _count?: true | SourcesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SourcesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SourcesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SourcesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SourcesMaxAggregateInputType
}

export type GetSourcesAggregateType<T extends SourcesAggregateArgs> = {
      [P in keyof T & keyof AggregateSources]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSources[P]>
    : Prisma.GetScalarType<T[P], AggregateSources[P]>
}




export type SourcesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourcesWhereInput
  orderBy?: Prisma.SourcesOrderByWithAggregationInput | Prisma.SourcesOrderByWithAggregationInput[]
  by: Prisma.SourcesScalarFieldEnum[] | Prisma.SourcesScalarFieldEnum
  having?: Prisma.SourcesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourcesCountAggregateInputType | true
  _avg?: SourcesAvgAggregateInputType
  _sum?: SourcesSumAggregateInputType
  _min?: SourcesMinAggregateInputType
  _max?: SourcesMaxAggregateInputType
}

export type SourcesGroupByOutputType = {
  id: number
  name: string
  isActive: boolean
  lastPrice: runtime.Decimal | null
  weight: number
  _count: SourcesCountAggregateOutputType | null
  _avg: SourcesAvgAggregateOutputType | null
  _sum: SourcesSumAggregateOutputType | null
  _min: SourcesMinAggregateOutputType | null
  _max: SourcesMaxAggregateOutputType | null
}

export type GetSourcesGroupByPayload<T extends SourcesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SourcesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SourcesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourcesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourcesGroupByOutputType[P]>
      }
    >
  >



export type SourcesWhereInput = {
  AND?: Prisma.SourcesWhereInput | Prisma.SourcesWhereInput[]
  OR?: Prisma.SourcesWhereInput[]
  NOT?: Prisma.SourcesWhereInput | Prisma.SourcesWhereInput[]
  id?: Prisma.IntFilter<"Sources"> | number
  name?: Prisma.StringFilter<"Sources"> | string
  isActive?: Prisma.BoolFilter<"Sources"> | boolean
  lastPrice?: Prisma.DecimalNullableFilter<"Sources"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFilter<"Sources"> | number
  exchangeRates?: Prisma.ExchangeRateListRelationFilter
}

export type SourcesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  lastPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  weight?: Prisma.SortOrder
  exchangeRates?: Prisma.ExchangeRateOrderByRelationAggregateInput
}

export type SourcesWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SourcesWhereInput | Prisma.SourcesWhereInput[]
  OR?: Prisma.SourcesWhereInput[]
  NOT?: Prisma.SourcesWhereInput | Prisma.SourcesWhereInput[]
  name?: Prisma.StringFilter<"Sources"> | string
  isActive?: Prisma.BoolFilter<"Sources"> | boolean
  lastPrice?: Prisma.DecimalNullableFilter<"Sources"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFilter<"Sources"> | number
  exchangeRates?: Prisma.ExchangeRateListRelationFilter
}, "id">

export type SourcesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  lastPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  weight?: Prisma.SortOrder
  _count?: Prisma.SourcesCountOrderByAggregateInput
  _avg?: Prisma.SourcesAvgOrderByAggregateInput
  _max?: Prisma.SourcesMaxOrderByAggregateInput
  _min?: Prisma.SourcesMinOrderByAggregateInput
  _sum?: Prisma.SourcesSumOrderByAggregateInput
}

export type SourcesScalarWhereWithAggregatesInput = {
  AND?: Prisma.SourcesScalarWhereWithAggregatesInput | Prisma.SourcesScalarWhereWithAggregatesInput[]
  OR?: Prisma.SourcesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SourcesScalarWhereWithAggregatesInput | Prisma.SourcesScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Sources"> | number
  name?: Prisma.StringWithAggregatesFilter<"Sources"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"Sources"> | boolean
  lastPrice?: Prisma.DecimalNullableWithAggregatesFilter<"Sources"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatWithAggregatesFilter<"Sources"> | number
}

export type SourcesCreateInput = {
  name: string
  isActive?: boolean
  lastPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: number
  exchangeRates?: Prisma.ExchangeRateCreateNestedManyWithoutSourceInput
}

export type SourcesUncheckedCreateInput = {
  id?: number
  name: string
  isActive?: boolean
  lastPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: number
  exchangeRates?: Prisma.ExchangeRateUncheckedCreateNestedManyWithoutSourceInput
}

export type SourcesUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  exchangeRates?: Prisma.ExchangeRateUpdateManyWithoutSourceNestedInput
}

export type SourcesUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  exchangeRates?: Prisma.ExchangeRateUncheckedUpdateManyWithoutSourceNestedInput
}

export type SourcesCreateManyInput = {
  id?: number
  name: string
  isActive?: boolean
  lastPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: number
}

export type SourcesUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type SourcesUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type SourcesScalarRelationFilter = {
  is?: Prisma.SourcesWhereInput
  isNot?: Prisma.SourcesWhereInput
}

export type SourcesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  lastPrice?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type SourcesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lastPrice?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type SourcesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  lastPrice?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type SourcesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  lastPrice?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type SourcesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lastPrice?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type SourcesCreateNestedOneWithoutExchangeRatesInput = {
  create?: Prisma.XOR<Prisma.SourcesCreateWithoutExchangeRatesInput, Prisma.SourcesUncheckedCreateWithoutExchangeRatesInput>
  connectOrCreate?: Prisma.SourcesCreateOrConnectWithoutExchangeRatesInput
  connect?: Prisma.SourcesWhereUniqueInput
}

export type SourcesUpdateOneRequiredWithoutExchangeRatesNestedInput = {
  create?: Prisma.XOR<Prisma.SourcesCreateWithoutExchangeRatesInput, Prisma.SourcesUncheckedCreateWithoutExchangeRatesInput>
  connectOrCreate?: Prisma.SourcesCreateOrConnectWithoutExchangeRatesInput
  upsert?: Prisma.SourcesUpsertWithoutExchangeRatesInput
  connect?: Prisma.SourcesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SourcesUpdateToOneWithWhereWithoutExchangeRatesInput, Prisma.SourcesUpdateWithoutExchangeRatesInput>, Prisma.SourcesUncheckedUpdateWithoutExchangeRatesInput>
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SourcesCreateWithoutExchangeRatesInput = {
  name: string
  isActive?: boolean
  lastPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: number
}

export type SourcesUncheckedCreateWithoutExchangeRatesInput = {
  id?: number
  name: string
  isActive?: boolean
  lastPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: number
}

export type SourcesCreateOrConnectWithoutExchangeRatesInput = {
  where: Prisma.SourcesWhereUniqueInput
  create: Prisma.XOR<Prisma.SourcesCreateWithoutExchangeRatesInput, Prisma.SourcesUncheckedCreateWithoutExchangeRatesInput>
}

export type SourcesUpsertWithoutExchangeRatesInput = {
  update: Prisma.XOR<Prisma.SourcesUpdateWithoutExchangeRatesInput, Prisma.SourcesUncheckedUpdateWithoutExchangeRatesInput>
  create: Prisma.XOR<Prisma.SourcesCreateWithoutExchangeRatesInput, Prisma.SourcesUncheckedCreateWithoutExchangeRatesInput>
  where?: Prisma.SourcesWhereInput
}

export type SourcesUpdateToOneWithWhereWithoutExchangeRatesInput = {
  where?: Prisma.SourcesWhereInput
  data: Prisma.XOR<Prisma.SourcesUpdateWithoutExchangeRatesInput, Prisma.SourcesUncheckedUpdateWithoutExchangeRatesInput>
}

export type SourcesUpdateWithoutExchangeRatesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type SourcesUncheckedUpdateWithoutExchangeRatesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
}


/**
 * Count Type SourcesCountOutputType
 */

export type SourcesCountOutputType = {
  exchangeRates: number
}

export type SourcesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  exchangeRates?: boolean | SourcesCountOutputTypeCountExchangeRatesArgs
}

/**
 * SourcesCountOutputType without action
 */
export type SourcesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourcesCountOutputType
   */
  select?: Prisma.SourcesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SourcesCountOutputType without action
 */
export type SourcesCountOutputTypeCountExchangeRatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExchangeRateWhereInput
}


export type SourcesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  isActive?: boolean
  lastPrice?: boolean
  weight?: boolean
  exchangeRates?: boolean | Prisma.Sources$exchangeRatesArgs<ExtArgs>
  _count?: boolean | Prisma.SourcesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sources"]>

export type SourcesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  isActive?: boolean
  lastPrice?: boolean
  weight?: boolean
}, ExtArgs["result"]["sources"]>

export type SourcesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  isActive?: boolean
  lastPrice?: boolean
  weight?: boolean
}, ExtArgs["result"]["sources"]>

export type SourcesSelectScalar = {
  id?: boolean
  name?: boolean
  isActive?: boolean
  lastPrice?: boolean
  weight?: boolean
}

export type SourcesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "isActive" | "lastPrice" | "weight", ExtArgs["result"]["sources"]>
export type SourcesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  exchangeRates?: boolean | Prisma.Sources$exchangeRatesArgs<ExtArgs>
  _count?: boolean | Prisma.SourcesCountOutputTypeDefaultArgs<ExtArgs>
}
export type SourcesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SourcesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SourcesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Sources"
  objects: {
    exchangeRates: Prisma.$ExchangeRatePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    isActive: boolean
    lastPrice: runtime.Decimal | null
    weight: number
  }, ExtArgs["result"]["sources"]>
  composites: {}
}

export type SourcesGetPayload<S extends boolean | null | undefined | SourcesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SourcesPayload, S>

export type SourcesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SourcesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SourcesCountAggregateInputType | true
  }

export interface SourcesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Sources'], meta: { name: 'Sources' } }
  /**
   * Find zero or one Sources that matches the filter.
   * @param {SourcesFindUniqueArgs} args - Arguments to find a Sources
   * @example
   * // Get one Sources
   * const sources = await prisma.sources.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SourcesFindUniqueArgs>(args: Prisma.SelectSubset<T, SourcesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Sources that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SourcesFindUniqueOrThrowArgs} args - Arguments to find a Sources
   * @example
   * // Get one Sources
   * const sources = await prisma.sources.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SourcesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SourcesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sources that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourcesFindFirstArgs} args - Arguments to find a Sources
   * @example
   * // Get one Sources
   * const sources = await prisma.sources.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SourcesFindFirstArgs>(args?: Prisma.SelectSubset<T, SourcesFindFirstArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sources that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourcesFindFirstOrThrowArgs} args - Arguments to find a Sources
   * @example
   * // Get one Sources
   * const sources = await prisma.sources.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SourcesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SourcesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sources that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourcesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sources
   * const sources = await prisma.sources.findMany()
   * 
   * // Get first 10 Sources
   * const sources = await prisma.sources.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sourcesWithIdOnly = await prisma.sources.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SourcesFindManyArgs>(args?: Prisma.SelectSubset<T, SourcesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Sources.
   * @param {SourcesCreateArgs} args - Arguments to create a Sources.
   * @example
   * // Create one Sources
   * const Sources = await prisma.sources.create({
   *   data: {
   *     // ... data to create a Sources
   *   }
   * })
   * 
   */
  create<T extends SourcesCreateArgs>(args: Prisma.SelectSubset<T, SourcesCreateArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sources.
   * @param {SourcesCreateManyArgs} args - Arguments to create many Sources.
   * @example
   * // Create many Sources
   * const sources = await prisma.sources.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SourcesCreateManyArgs>(args?: Prisma.SelectSubset<T, SourcesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Sources and returns the data saved in the database.
   * @param {SourcesCreateManyAndReturnArgs} args - Arguments to create many Sources.
   * @example
   * // Create many Sources
   * const sources = await prisma.sources.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Sources and only return the `id`
   * const sourcesWithIdOnly = await prisma.sources.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SourcesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SourcesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Sources.
   * @param {SourcesDeleteArgs} args - Arguments to delete one Sources.
   * @example
   * // Delete one Sources
   * const Sources = await prisma.sources.delete({
   *   where: {
   *     // ... filter to delete one Sources
   *   }
   * })
   * 
   */
  delete<T extends SourcesDeleteArgs>(args: Prisma.SelectSubset<T, SourcesDeleteArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Sources.
   * @param {SourcesUpdateArgs} args - Arguments to update one Sources.
   * @example
   * // Update one Sources
   * const sources = await prisma.sources.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SourcesUpdateArgs>(args: Prisma.SelectSubset<T, SourcesUpdateArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sources.
   * @param {SourcesDeleteManyArgs} args - Arguments to filter Sources to delete.
   * @example
   * // Delete a few Sources
   * const { count } = await prisma.sources.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SourcesDeleteManyArgs>(args?: Prisma.SelectSubset<T, SourcesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourcesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sources
   * const sources = await prisma.sources.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SourcesUpdateManyArgs>(args: Prisma.SelectSubset<T, SourcesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sources and returns the data updated in the database.
   * @param {SourcesUpdateManyAndReturnArgs} args - Arguments to update many Sources.
   * @example
   * // Update many Sources
   * const sources = await prisma.sources.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Sources and only return the `id`
   * const sourcesWithIdOnly = await prisma.sources.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SourcesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SourcesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Sources.
   * @param {SourcesUpsertArgs} args - Arguments to update or create a Sources.
   * @example
   * // Update or create a Sources
   * const sources = await prisma.sources.upsert({
   *   create: {
   *     // ... data to create a Sources
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Sources we want to update
   *   }
   * })
   */
  upsert<T extends SourcesUpsertArgs>(args: Prisma.SelectSubset<T, SourcesUpsertArgs<ExtArgs>>): Prisma.Prisma__SourcesClient<runtime.Types.Result.GetResult<Prisma.$SourcesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourcesCountArgs} args - Arguments to filter Sources to count.
   * @example
   * // Count the number of Sources
   * const count = await prisma.sources.count({
   *   where: {
   *     // ... the filter for the Sources we want to count
   *   }
   * })
  **/
  count<T extends SourcesCountArgs>(
    args?: Prisma.Subset<T, SourcesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourcesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Sources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourcesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SourcesAggregateArgs>(args: Prisma.Subset<T, SourcesAggregateArgs>): Prisma.PrismaPromise<GetSourcesAggregateType<T>>

  /**
   * Group by Sources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourcesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SourcesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SourcesGroupByArgs['orderBy'] }
      : { orderBy?: SourcesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SourcesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSourcesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Sources model
 */
readonly fields: SourcesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Sources.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SourcesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  exchangeRates<T extends Prisma.Sources$exchangeRatesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Sources$exchangeRatesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExchangeRatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Sources model
 */
export interface SourcesFieldRefs {
  readonly id: Prisma.FieldRef<"Sources", 'Int'>
  readonly name: Prisma.FieldRef<"Sources", 'String'>
  readonly isActive: Prisma.FieldRef<"Sources", 'Boolean'>
  readonly lastPrice: Prisma.FieldRef<"Sources", 'Decimal'>
  readonly weight: Prisma.FieldRef<"Sources", 'Float'>
}
    

// Custom InputTypes
/**
 * Sources findUnique
 */
export type SourcesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * Filter, which Sources to fetch.
   */
  where: Prisma.SourcesWhereUniqueInput
}

/**
 * Sources findUniqueOrThrow
 */
export type SourcesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * Filter, which Sources to fetch.
   */
  where: Prisma.SourcesWhereUniqueInput
}

/**
 * Sources findFirst
 */
export type SourcesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * Filter, which Sources to fetch.
   */
  where?: Prisma.SourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sources to fetch.
   */
  orderBy?: Prisma.SourcesOrderByWithRelationInput | Prisma.SourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sources.
   */
  cursor?: Prisma.SourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sources.
   */
  distinct?: Prisma.SourcesScalarFieldEnum | Prisma.SourcesScalarFieldEnum[]
}

/**
 * Sources findFirstOrThrow
 */
export type SourcesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * Filter, which Sources to fetch.
   */
  where?: Prisma.SourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sources to fetch.
   */
  orderBy?: Prisma.SourcesOrderByWithRelationInput | Prisma.SourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sources.
   */
  cursor?: Prisma.SourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sources.
   */
  distinct?: Prisma.SourcesScalarFieldEnum | Prisma.SourcesScalarFieldEnum[]
}

/**
 * Sources findMany
 */
export type SourcesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * Filter, which Sources to fetch.
   */
  where?: Prisma.SourcesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sources to fetch.
   */
  orderBy?: Prisma.SourcesOrderByWithRelationInput | Prisma.SourcesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Sources.
   */
  cursor?: Prisma.SourcesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sources.
   */
  distinct?: Prisma.SourcesScalarFieldEnum | Prisma.SourcesScalarFieldEnum[]
}

/**
 * Sources create
 */
export type SourcesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * The data needed to create a Sources.
   */
  data: Prisma.XOR<Prisma.SourcesCreateInput, Prisma.SourcesUncheckedCreateInput>
}

/**
 * Sources createMany
 */
export type SourcesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Sources.
   */
  data: Prisma.SourcesCreateManyInput | Prisma.SourcesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sources createManyAndReturn
 */
export type SourcesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * The data used to create many Sources.
   */
  data: Prisma.SourcesCreateManyInput | Prisma.SourcesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sources update
 */
export type SourcesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * The data needed to update a Sources.
   */
  data: Prisma.XOR<Prisma.SourcesUpdateInput, Prisma.SourcesUncheckedUpdateInput>
  /**
   * Choose, which Sources to update.
   */
  where: Prisma.SourcesWhereUniqueInput
}

/**
 * Sources updateMany
 */
export type SourcesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Sources.
   */
  data: Prisma.XOR<Prisma.SourcesUpdateManyMutationInput, Prisma.SourcesUncheckedUpdateManyInput>
  /**
   * Filter which Sources to update
   */
  where?: Prisma.SourcesWhereInput
  /**
   * Limit how many Sources to update.
   */
  limit?: number
}

/**
 * Sources updateManyAndReturn
 */
export type SourcesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * The data used to update Sources.
   */
  data: Prisma.XOR<Prisma.SourcesUpdateManyMutationInput, Prisma.SourcesUncheckedUpdateManyInput>
  /**
   * Filter which Sources to update
   */
  where?: Prisma.SourcesWhereInput
  /**
   * Limit how many Sources to update.
   */
  limit?: number
}

/**
 * Sources upsert
 */
export type SourcesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * The filter to search for the Sources to update in case it exists.
   */
  where: Prisma.SourcesWhereUniqueInput
  /**
   * In case the Sources found by the `where` argument doesn't exist, create a new Sources with this data.
   */
  create: Prisma.XOR<Prisma.SourcesCreateInput, Prisma.SourcesUncheckedCreateInput>
  /**
   * In case the Sources was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SourcesUpdateInput, Prisma.SourcesUncheckedUpdateInput>
}

/**
 * Sources delete
 */
export type SourcesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
  /**
   * Filter which Sources to delete.
   */
  where: Prisma.SourcesWhereUniqueInput
}

/**
 * Sources deleteMany
 */
export type SourcesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sources to delete
   */
  where?: Prisma.SourcesWhereInput
  /**
   * Limit how many Sources to delete.
   */
  limit?: number
}

/**
 * Sources.exchangeRates
 */
export type Sources$exchangeRatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExchangeRate
   */
  select?: Prisma.ExchangeRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExchangeRate
   */
  omit?: Prisma.ExchangeRateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExchangeRateInclude<ExtArgs> | null
  where?: Prisma.ExchangeRateWhereInput
  orderBy?: Prisma.ExchangeRateOrderByWithRelationInput | Prisma.ExchangeRateOrderByWithRelationInput[]
  cursor?: Prisma.ExchangeRateWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExchangeRateScalarFieldEnum | Prisma.ExchangeRateScalarFieldEnum[]
}

/**
 * Sources without action
 */
export type SourcesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sources
   */
  select?: Prisma.SourcesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sources
   */
  omit?: Prisma.SourcesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourcesInclude<ExtArgs> | null
}
